export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'
export const FETCH_MEMBER = 'FETCH_MEMBER'

export const FETCH_AUTH = 'FETCH_AUTH'
export const FETCH_AUTH_LIST = 'FETCH_AUTH_LIST'


export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'
export const FETCH_BOARD_COMMENTS_LIST = 'FETCH_BOARD_COMMENTS_LIST'
export const FETCH_BOARD_ID_LISTS = 'FETCH_BOARD_ID_LISTS'


export const FETCH_RESERVATION = 'FETCH_RESERVATION'
export const FETCH_RESERVATION_LIST = 'FETCH_RESERVATION_LIST'
export const FETCH_RESERVATION_ID_LISTS = 'FETCH_RESERVATION_ID_LISTS'


export const FETCH_NOTICE_BOARD_LIST = 'FETCH_NOTICE_BOARD_LIST'
export const FETCH_NOTICE_BOARD = 'FETCH_NOTICE_BOARD'

export const FETCH_CENTER_LIST = 'FETCH_CENTER_LIST'
export const FETCH_CENTER = 'FETCH_CENTER'
export const FETCH_CENTER_COMMENTS_LIST = 'FETCH_CENTER_COMMENTS_LIST'
export const FETCH_CENTER_ID_LISTS = 'FETCH_CENTER_ID_LISTS'

export const FETCH_REGISTER_MEMBERS = 'FETCH_REGISTER_MEMBERS'
export const FETCH_REGISTER_MEMBER = 'FETCH_REGISTER_MEMBER'
export const FETCH_REGISTER_MEMBER_AUTHS = 'FETCH_REGISTER_MEMBER_AUTHS'
export const FETCH_REGISTER_MEMBER_AUTH = 'FETCH_REGISTER_MEMBER_AUTH'




